🌟 feat: add datepicker
vote4hk/warsinhk pull request #118
Opened 2020-02-09 04:28 UTC by wingkwong

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] i18n translation has been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ..., provide screenshots if necessary)
feature

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
add datepicker

2020-02-09 08:23 UTC, nandiheath requested changes

2020-02-09 08:23 UTC, nandiheath commented on src/utils/search.js
> +  console.log(node)
console.log

2020-02-09 08:23 UTC, nandiheath commented on src/pages/high-risk.js
> +              console.log(selectedArray)
console.log

2020-02-09 15:01 UTC, cswbrian commented
There's some z-index issue between search and datepicker component
![image](https://user-images.githubusercontent.com/9110909/74104490-14873300-4b90-11ea-8ac0-6c41a55a5adc.png)

2020-02-09 15:05 UTC, cswbrian commented
The datepicker should filter any cards which overlap the selected range,

i.e. if I select 2020-02-01 -> 2020-02-15
the card of 2020-01-30 - 2020-02-14 should also appear

2020-02-09 15:56 UTC, wingkwong commented
> The datepicker should filter any cards which overlap the selected range,
> 
> i.e. if I select 2020-02-01 -> 2020-02-15
> the card of 2020-01-30 - 2020-02-14 should also appear

![image](https://user-images.githubusercontent.com/35857179/74105308-9c247000-4b97-11ea-812b-2727d4f356ca.png)

2020-02-10 02:48 UTC, cswbrian commented
The close button of datepicker is not working in desktop view.
Can you also change the date format to DD/MM/YYYY?
![image](https://user-images.githubusercontent.com/9110909/74117483-c5261e80-4bf2-11ea-97d7-e1ec43c5b6fc.png)

2020-02-10 04:34 UTC, wingkwong commented
> The close button of datepicker is not working in desktop view.
> Can you also change the date format to DD/MM/YYYY?
> ![image](https://user-images.githubusercontent.com/9110909/74117483-c5261e80-4bf2-11ea-97d7-e1ec43c5b6fc.png)

@cswbrian 
1. I think it was due to the z-index fix. However, the z-index issue cannot be reproduced now on my side after rollbacking that change. The behaviour I noticed is that the datepicker will be closed if I click on AsyncSelect. Not sure why.

2. Added ``displayFormat``

2020-02-10 09:02 UTC, merged