enh: Support search by case number
vote4hk/warsinhk pull request #192
Opened 2020-04-01 04:27 UTC by poyea

Fixes #191 for now.
This patch enables search by case number in cases page. The number of
entries for number is limited to 3.

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] i18n translation has been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ..., provide screenshots if necessary)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2020-04-02 13:52 UTC, nandiheath requested changes
Awesome! Sorry for my messy code but you can still add function on it!

2020-04-02 13:52 UTC, nandiheath commented on src/utils/search.js
> +    .map(({ node }) => node.case_no)
should be `.map(({ node }) => node[field] || '' )` ?

2020-04-03 05:57 UTC, poyea commented
> Awesome! Sorry for my messy code but you can still add function on it!

I just deleted that for simplicity. haha

> should be `.map(({ node }) => node[field] || '' )` ?

With that context it's the same, but I changed to this in the newer `createDedupOptions()` . It also facilitate the search.

2020-04-03 12:20 UTC, nandiheath approved these changes

2020-04-03 12:20 UTC, merged