fix official name and translation
vote4hk/warsinhk pull request #29
Opened 2020-01-29 08:33 UTC by csvke

Update the official name, descriptions and keywords according to Health Department Hong Kong in response to a bug report

2020-01-29 08:47 UTC, cswbrian requested changes

2020-01-29 08:47 UTC, cswbrian commented on src/locales/zh/translation.json
> -  "site.title": "🤒武漢肺炎民間資訊😷",
indeed I prefer
`武漢肺炎民間資訊` and `2019-nCoV (WARS) Info`

It is so common for the media to use the nickname
https://www.google.com/search?q=%E6%AD%A6%E6%BC%A2%E8%82%BA%E7%82%8E&sxsrf=ACYBGNShn5AtIdbSOJB7C0Fzo_RyGUWpMQ:1580287576458&source=lnms&tbm=nws&sa=X&ved=2ahUKEwim2oz9tajnAhXY7WEKHU1UCvEQ_AUoAXoECA4QAw&biw=1684&bih=844

2020-01-29 11:54 UTC, nandiheath requested changes
please rebase to latest dev and also please stay with the simpler name 🤣

2020-02-02 09:57 UTC, nandiheath commented
localizations are already up to date
thanks @csvke

2020-02-02 09:57 UTC, closed without merging