refactor: improve landing page loading performance
vote4hk/warsinhk pull request #75
Opened 2020-02-02 08:16 UTC by tonyhhyip

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] i18n translation has been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ..., provide screenshots if necessary)
Improve landing page loading performance

Average Load: 1.50 s -> 1.10 s
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2020-02-02 10:09 UTC, nandiheath requested changes
~i prefer KISS principle unless there is a proof of significant performance boost 🙂~
ah sorry I missed your message. so you mean the `useMemo` can reduce the number of rendering?

2020-02-02 10:09 UTC, nandiheath commented on src/pages/index.js
> +  const latestStat = React.useMemo(() => data.allDailyStats.edges[0].node, [
what is the purpose of useMemo here?

2020-02-03 03:11 UTC, tonyhhyip commented
@nandiheath do you still need me to make changes?

2020-02-04 05:59 UTC, nandiheath approved these changes

2020-02-04 05:59 UTC, merged

2020-02-04 06:00 UTC, nandiheath commented
> @nandiheath do you still need me to make changes?

sorry missed that 🤦‍♂️